# from: https://github.com/amazon-archives/serverless-app-examples/blob/master/python/hello-world-python3/template.yaml
# SAM FILE
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler   # app is the file in src
      Runtime: python3.9
      CodeUri: src/                 # point to work dir
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3